version: '3.9'

services:
  backend:
    image: node:14
    # build: 
    #   context: ./back-end/
    #   dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./back-end:/app
  frontend:
    image: node:14
    # build: 
    #   context: ./front-end/
    #   dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./front-end:/app
  dbmysql:
    build: 
      context: ./db
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=2153
    ports:
      - 3307:3306
    volumes:
      - ./db/data:/var/lib/mysql

    